name: Bug Report
description: Report a bug or issue with Stratify AI
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down/data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue/cosmetic)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - Dashboard
        - Documents
        - OGSM Platform
        - KPIs
        - AI Strategy Generator
        - Strategic Planning
        - Reports
        - AI Chief Strategy Officer
        - Authentication
        - Database
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually occurred
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      value: |
        - OS: [e.g., Windows 11, macOS 14]
        - Browser: [e.g., Chrome 120, Firefox 121]
        - Stratify AI Version: [e.g., 1.0.0]
        - Deployment: [Docker/Local Dev]
      render: markdown
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: If available, paste any relevant error logs or console output
      placeholder: Paste error logs here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Any other relevant information
    validations:
      required: false
